import os

src_dir = r"c:\Users\marua\Desktop\proyects\ardi-sl\src\i18n\dictionaries"
es_path = os.path.join(src_dir, "es.ts")
fr_path = os.path.join(src_dir, "fr.ts")

es_block = """
  ],
  components: {
    hero: {
      locationBadge: "Fabricantes en Oiartzun (Gipuzkoa)",
      sinceBadge: "Desde 1990",
      titleStart: "Maquinaria y Calderería en ",
      titleHighlight: "Acero Inoxidable",
      titleEnd: " para Queserías",
      descStart: "Especialistas en el diseño, fabricación a medida y montaje de cubas de cuajado, arcones desueradores, prensas y líneas automáticas. Calidad certificada en ",
      descHighlight: "AISI 304 y AISI 316L",
      descEnd: " para obradores artesanos y grandes plantas industriales.",
      exploreBtn: "Explorar Catálogo de Equipos",
      quoteBtn: "Solicitar Presupuesto",
      ceMark: "Marcado CE oficial",
      tigWeld: "Soldadura TIG sanitaria",
      onSite: "Montaje in situ en quesería",
      prodLines: "Líneas de Producción",
      inProd: "En fabricación",
      card1Title: "Cubas de Cuajar Holandesa",
      card1Sub: "300L - 5.000L",
      card1Desc: "Corte mecanizado por liras con variador e intercambio térmico con camisa.",
      card2Title: "Arcones y Prensas Neumáticas",
      card2Sub: "Presión digital",
      card2Desc: "Desuerado continuo con microperforación desmontable y prensado por columnas.",
      card3Title: "Líneas Llave en Mano",
      card3Sub: "Automatizadas",
      card3Desc: "Proyectos completos desde recepción y pasterización hasta limpieza CIP.",
      adviseBtn: "Pedir asesoramiento técnico directo"
    },
    about: {
      historyBadge: "Más de Tres Décadas de Trayectoria",
      titleStart: "Tradición en Calderería y Vanguardia en ",
      titleHighlight: "Maquinaria Sanitaria",
      desc1Start: "Fundada en 1990 en el ",
      desc1Highlight1: "Polígono Industrial Pagoaldea de Oiartzun (Gipuzkoa)",
      desc1Mid: ", en ",
      desc1Highlight2: "ARDI SL",
      desc1End: " nos hemos consolidado como referente en el diseño y fabricación integral de maquinaria en acero inoxidable para la industria láctea, quesera y alimentaria.",
      desc2: "Nuestro valor diferencial reside en el dominio exhaustivo de la calderería fina y la soldadura sanitaria TIG con purga de argón interior. No somos meros distribuidores: construimos cada cuba, cada arcón desuerador y cada línea de prensado a partir de chapa y perfiles de aceros nobles AISI 304 y 316L, dotando a cada equipo de robustez mecánica y acabados sanitarios impecables sin recovecos.",
      ceTitle: "Marcado CE Oficial",
      ceDesc: "Cumplimiento estricto de la directiva de máquinas 2006/42/CE.",
      steelTitle: "Acero AISI 316L",
      steelDesc: "Resistencia superior a cloruros, salmueras y ácidos de limpieza.",
      imgTitle: "Instalaciones Propias en Oiartzun",
      imgSub: "Pabellón 65, Polígono Pagoaldea",
      imgBadge: "Gipuzkoa",
      pillarsTitle: "Los Cuatro Pilares de Calidad ARDI",
      pillarsDesc: "Riguroso estándar de diseño mecánico y seguridad biológica en cada componente.",
      methodBadge: "Metodología de Trabajo",
      methodTitle: "De la Idea a la Primera Cuajada",
      methodDesc: "Un proceso riguroso y transparente paso a paso para asegurar el éxito de su inversión."
    },
    contact: {
      directAttention: "Atención Directa al Profesional",
      titleStart: "Contacte con Nuestro ",
      titleHighlight: "Equipo Técnico",
      desc: "Estamos en Oiartzun a su entera disposición. Consúltenos cualquier duda sobre dimensiones, capacidades, plazos de entrega o solicite presupuesto sin compromiso.",
      phonesTitle: "Teléfonos de Atención",
      emailTitle: "Correo Electrónico",
      hqTitle: "Sede y Taller Central",
      country: "España",
      hoursTitle: "Horario de Fabricación y Atención",
      mapsBtn: "Ver ubicación en Google Maps",
      successTitle: "¡Mensaje Recibido Correctamente!",
      successDesc1: "Muchas gracias, ",
      successDesc2: ". Hemos recibido su consulta sobre ",
      successDesc3: ". En un plazo máximo de 24 horas laborables un técnico comercial le responderá.",
      successBtn: "Enviar otra consulta",
      formTitle: "Formulario de Solicitud de Información",
      formMandatory: "* Campos obligatorios",
      lblName: "Nombre y Apellidos / Empresa *",
      phName: "Ej. Juan Pérez - Quesos del Valle",
      lblEmail: "Correo Electrónico *",
      phEmail: "contacto@ejemplo.com",
      lblPhone: "Teléfono de Contacto *",
      phPhone: "+34 600 000 000",
      lblSubject: "Asunto / Línea de Interés *",
      opt1: "Solicitar presupuesto de maquinaria",
      opt2: "Cubas de Elaboración (Holandesa / Doblecero)",
      opt3: "Arcón Desuerador y Preprensado",
      opt4: "Prensas de Quesos Neumáticas",
      opt5: "Túnel de Lavado de Moldes",
      opt6: "Distribuidor de Leche y Válvulas Inox",
      opt7: "Proyecto Llave en Mano de Quesería",
      opt8: "Calderería y Carpintería Metálica a Medida",
      opt9: "Suministros y Recambios Sanitarios",
      opt10: "Otro asunto técnico",
      lblMsg: "Mensaje / Requerimientos Técnicos *",
      phMsg: "Describa el equipo, volumen diario de leche, dimensiones disponibles o dudas técnicas...",
      privacyPrefix: "He leído y acepto la ",
      privacyLink: "política de privacidad y protección de datos",
      privacySuffix: " para la gestión y respuesta de mi solicitud comercial.",
      btnSubmitting: "Enviando mensaje...",
      btnSubmit: "Enviar Mensaje a ARDI SL",
      errName: "Por favor, indique su nombre o empresa.",
      errEmail: "Introduzca un correo electrónico válido.",
      errPhone: "Indique un teléfono para que podamos contactarle.",
      errMsg: "El mensaje debe contener al menos 10 caracteres explicativos.",
      errPrivacy: "Debe aceptar la política de privacidad para enviar la consulta.",
      msgSuccess: "¡Mensaje enviado con éxito! Nos pondremos en contacto con usted a la mayor brevedad.",
      copied: "copiado al portapapeles"
    },
    footer: {
      brandSub: "Maquinaria & Calderería Inox",
      brandDesc: "Desde 1990 fabricando maquinaria en acero inoxidable AISI 304/316L para queserías y la industria agroalimentaria. Ingeniería propia, solidez mecánica y compromiso sanitario.",
      ceMark: "Marcado CE según Directiva 2006/42/CE",
      navTitle: "Navegación",
      navHome: "Inicio",
      navCatalog: "Catálogo de Productos",
      navAbout: "Quiénes Somos",
      navMethod: "Metodología",
      navContact: "Contacto & Ubicación",
      linesTitle: "Líneas de Maquinaria",
      contactTitle: "Contacto Oiartzun",
      rights: "Todos los derechos reservados.",
      legalNotice: "Aviso Legal",
      privacyPolicy: "Política de Privacidad",
      cookiesPolicy: "Política de Cookies",
      location: "Oiartzun • Gipuzkoa (País Vasco)",
      backTop: "Volver arriba"
    },
    header: {
      barLoc: "Oiartzun (Gipuzkoa) • Fabricación propia en acero inox",
      barCe: "Marcado CE y Calidad Alimentaria AISI 304/316L",
      brandSub: "Maquinaria & Calderería Inox",
      btnQuote: "Solicitar presupuesto"
    },
    catalog: {
      titleStart: "Catálogo de ",
      titleHighlight: "Maquinaria Industrial",
      desc: "Equipos fabricados a medida en acero inoxidable AISI 304/316L, diseñados para maximizar el rendimiento y garantizar la máxima higiene en el sector lácteo.",
      filterLbl: "Filtrar catálogo:",
      filterAll: "Todos los Equipos",
      badgeCustom: "Fabricación a medida",
      btnView: "Ver Ficha Técnica",
      btnQuote: "Cotizar",
      ctaTitle: "¿No encuentra el equipo exacto para su línea de producción?",
      ctaDesc: "Nuestro departamento de ingeniería (Oficina Técnica) desarrolla soluciones personalizadas y realiza modificaciones sobre catálogo para adaptarnos 100% al espacio y capacidad de su quesería.",
      ctaBtn: "Consultar Fabricación a Medida"
    }
  }
};
"""

fr_block = """
  ],
  components: {
    hero: {
      locationBadge: "Fabricants à Oiartzun (Gipuzkoa)",
      sinceBadge: "Depuis 1990",
      titleStart: "Machines et Chaudronnerie en ",
      titleHighlight: "Acier Inoxydable",
      titleEnd: " pour Fromageries",
      descStart: "Spécialistes dans la conception, la fabrication sur mesure et le montage de cuves de caillage, bacs d'égouttage, presses et lignes automatiques. Qualité certifiée en ",
      descHighlight: "AISI 304 et AISI 316L",
      descEnd: " pour ateliers artisanaux et grandes usines industrielles.",
      exploreBtn: "Explorer le Catalogue d'Équipements",
      quoteBtn: "Demander un Devis",
      ceMark: "Marquage CE officiel",
      tigWeld: "Soudure TIG sanitaire",
      onSite: "Montage sur site en fromagerie",
      prodLines: "Lignes de Production",
      inProd: "En fabrication",
      card1Title: "Cuves à Cailler Hollandaise",
      card1Sub: "300L - 5.000L",
      card1Desc: "Coupe mécanisée par tranche-caillés avec variateur et échange thermique avec chemise.",
      card2Title: "Bacs et Presses Pneumatiques",
      card2Sub: "Pression numérique",
      card2Desc: "Égouttage continu avec microperforation amovible et pressage par colonnes.",
      card3Title: "Lignes Clés en Main",
      card3Sub: "Automatisées",
      card3Desc: "Projets complets de la réception et pasteurisation jusqu'au nettoyage CIP.",
      adviseBtn: "Demander des conseils techniques directs"
    },
    about: {
      historyBadge: "Plus de Trois Décennies d'Expérience",
      titleStart: "Tradition en Chaudronnerie et Avant-garde en ",
      titleHighlight: "Machines Sanitaires",
      desc1Start: "Fondée en 1990 dans le ",
      desc1Highlight1: "Zone Industrielle Pagoaldea d'Oiartzun (Gipuzkoa)",
      desc1Mid: ", chez ",
      desc1Highlight2: "ARDI SL",
      desc1End: " nous nous sommes consolidés comme une référence dans la conception et la fabrication intégrale de machines en acier inoxydable pour l'industrie laitière, fromagère et agroalimentaire.",
      desc2: "Notre valeur ajoutée réside dans la maîtrise exhaustive de la chaudronnerie fine et de la soudure sanitaire TIG avec purge d'argon intérieur. Nous ne sommes pas de simples distributeurs : nous construisons chaque cuve, chaque bac d'égouttage et chaque ligne de pressage à partir de tôles et profilés en aciers nobles AISI 304 et 316L, dotant chaque équipement d'une robustesse mécanique et de finitions sanitaires impeccables sans recoins.",
      ceTitle: "Marquage CE Officiel",
      ceDesc: "Respect strict de la directive machines 2006/42/CE.",
      steelTitle: "Acier AISI 316L",
      steelDesc: "Résistance supérieure aux chlorures, saumures et acides de nettoyage.",
      imgTitle: "Installations Propres à Oiartzun",
      imgSub: "Pavillon 65, Zone Industrielle Pagoaldea",
      imgBadge: "Gipuzkoa",
      pillarsTitle: "Les Quatre Piliers de Qualité ARDI",
      pillarsDesc: "Norme rigoureuse de conception mécanique et de sécurité biologique dans chaque composant.",
      methodBadge: "Méthodologie de Travail",
      methodTitle: "De l'Idée au Premier Caillage",
      methodDesc: "Un processus rigoureux et transparent étape par étape pour assurer le succès de votre investissement."
    },
    contact: {
      directAttention: "Attention Directe aux Professionnels",
      titleStart: "Contactez Notre ",
      titleHighlight: "Équipe Technique",
      desc: "Nous sommes à Oiartzun à votre entière disposition. Consultez-nous pour toute question sur les dimensions, capacités, délais de livraison ou demandez un devis sans engagement.",
      phonesTitle: "Téléphones d'Assistance",
      emailTitle: "Courrier Électronique",
      hqTitle: "Siège et Atelier Central",
      country: "Espagne",
      hoursTitle: "Horaires de Fabrication et d'Assistance",
      mapsBtn: "Voir l'emplacement sur Google Maps",
      successTitle: "Message Reçu Correctement !",
      successDesc1: "Merci beaucoup, ",
      successDesc2: ". Nous avons reçu votre demande concernant ",
      successDesc3: ". Dans un délai maximum de 24 heures ouvrables, un technico-commercial vous répondra.",
      successBtn: "Envoyer une autre demande",
      formTitle: "Formulaire de Demande d'Information",
      formMandatory: "* Champs obligatoires",
      lblName: "Nom et Prénoms / Entreprise *",
      phName: "Ex. Jean Dupont - Fromages de la Vallée",
      lblEmail: "Courrier Électronique *",
      phEmail: "contact@exemple.com",
      lblPhone: "Téléphone de Contact *",
      phPhone: "+33 6 00 00 00 00",
      lblSubject: "Sujet / Ligne d'Intérêt *",
      opt1: "Demander un devis de machines",
      opt2: "Cuves d'Élaboration (Hollandaise / Double O)",
      opt3: "Bac d'Égouttage et Pré-pressage",
      opt4: "Presses à Fromages Pneumatiques",
      opt5: "Tunnel de Lavage de Moules",
      opt6: "Distributeur de Lait et Vannes Inox",
      opt7: "Projet Clés en Main de Fromagerie",
      opt8: "Chaudronnerie et Menuiserie Métallique sur Mesure",
      opt9: "Fournitures et Pièces de Rechange Sanitaires",
      opt10: "Autre sujet technique",
      lblMsg: "Message / Exigences Techniques *",
      phMsg: "Décrivez l'équipement, le volume quotidien de lait, les dimensions disponibles ou vos doutes techniques...",
      privacyPrefix: "J'ai lu et j'accepte la ",
      privacyLink: "politique de confidentialité et de protection des données",
      privacySuffix: " pour la gestion et la réponse à ma demande commerciale.",
      btnSubmitting: "Envoi du message...",
      btnSubmit: "Envoyer le Message à ARDI SL",
      errName: "Veuillez indiquer votre nom ou votre entreprise.",
      errEmail: "Veuillez saisir une adresse e-mail valide.",
      errPhone: "Veuillez indiquer un téléphone pour que nous puissions vous contacter.",
      errMsg: "Le message doit contenir au moins 10 caractères explicatifs.",
      errPrivacy: "Vous devez accepter la politique de confidentialité pour envoyer la demande.",
      msgSuccess: "Message envoyé avec succès ! Nous vous contacterons dans les plus brefs délais.",
      copied: "copié dans le presse-papiers"
    },
    footer: {
      brandSub: "Machines & Chaudronnerie Inox",
      brandDesc: "Depuis 1990, nous fabriquons des machines en acier inoxydable AISI 304/316L pour les fromageries et l'industrie agroalimentaire. Ingénierie propre, solidité mécanique et engagement sanitaire.",
      ceMark: "Marquage CE selon la Directive 2006/42/CE",
      navTitle: "Navigation",
      navHome: "Accueil",
      navCatalog: "Catalogue de Produits",
      navAbout: "Qui Sommes-Nous",
      navMethod: "Méthodologie",
      navContact: "Contact & Emplacement",
      linesTitle: "Lignes de Machines",
      contactTitle: "Contact Oiartzun",
      rights: "Tous droits réservés.",
      legalNotice: "Mentions Légales",
      privacyPolicy: "Politique de Confidentialité",
      cookiesPolicy: "Politique de Cookies",
      location: "Oiartzun • Gipuzkoa (Pays Basque)",
      backTop: "Retour en haut"
    },
    header: {
      barLoc: "Oiartzun (Gipuzkoa) • Fabrication propre en acier inox",
      barCe: "Marquage CE et Qualité Alimentaire AISI 304/316L",
      brandSub: "Machines & Chaudronnerie Inox",
      btnQuote: "Demander un devis"
    },
    catalog: {
      titleStart: "Catalogue de ",
      titleHighlight: "Machines Industrielles",
      desc: "Équipements fabriqués sur mesure en acier inoxydable AISI 304/316L, conçus pour maximiser le rendement et garantir une hygiène maximale dans le secteur laitier.",
      filterLbl: "Filtrer le catalogue :",
      filterAll: "Tous les Équipements",
      badgeCustom: "Fabrication sur mesure",
      btnView: "Voir Fiche Technique",
      btnQuote: "Obtenir un Devis",
      ctaTitle: "Vous ne trouvez pas l'équipement exact pour votre ligne de production ?",
      ctaDesc: "Notre département d'ingénierie (Bureau Technique) développe des solutions personnalisées et effectue des modifications sur catalogue pour s'adapter à 100% à l'espace et à la capacité de votre fromagerie.",
      ctaBtn: "Consulter pour Fabrication sur Mesure"
    }
  }
};
"""

with open(es_path, 'r', encoding='utf-8') as f:
    es_code = f.read()
    es_code = es_code.replace("  ]\n};", es_block)

with open(es_path, 'w', encoding='utf-8') as f:
    f.write(es_code)

with open(fr_path, 'r', encoding='utf-8') as f:
    fr_code = f.read()
    fr_code = fr_code.replace("  ]\n};", fr_block)

with open(fr_path, 'w', encoding='utf-8') as f:
    f.write(fr_code)
